### Register Admin
POST http://localhost:4000/api/admin/register
Content-Type: application/json

{
  "name": "Admin Carol",
  "email": "admin@example.com",
  "password": "Admin"
}

### Login Admin
POST http://localhost:4000/api/admin/login
Content-Type: application/json

{
  "email": "admin@example.com",
  "password": "admin"
}

###Update admin details
PUT http://localhost:4000/api/admin/2bfbc244-5da6-48ed-b7c3-5a64b97c7edf
Content-Type: application/json

{
  "name": "Admin Carol",
  "email": "admin@example.com",
  "password": "admin"
}

