### Register a Client
POST http://localhost:4000/api/clients/register
Content-Type: application/json

{
  "fname": "carol",
  "lname": "Doe",
  "age": 32,
  "gender": "Female",
  "phone": "0712345678",
  "email": "jane.doe@example.com"
}

### Get All Clients
GET http://localhost:4000/api/clients

### Get Client By ID
GET http://localhost:4000/api/clients/f513745e-d29c-48ae-9e81-105ac79253d9

### Update Client
PUT http://localhost:4000/api/clients/f513745e-d29c-48ae-9e81-105ac79253d9
Content-Type: application/json

{ "fname": "Janet",
  "lname": "Doe",
  "age": 32,
  "gender": "Female",
  "phone": "0712345678",
  "email": "janet.doe@example.com"
}

### Delete Client
DELETE http://localhost:4000/api/clients/d78abeea-4f5a-41b5-96a5-025b30c635b3
