### Create a health program
POST http://localhost:4000/api/programs
Content-Type: application/json

{
  "name": "deleted Program",
  "description": "Support and care for people living with HIV."
}

### Get all health programs
GET http://localhost:4000/api/programs

### Get a specific health program by ID
GET http://localhost:4000/api/programs/372a2009-de54-454e-b3a7-c2a351b3970a

###Update health program
PUT http://localhost:4000/api/programs/05d928d1-86be-4a8a-a7cd-0e405cc455e2
Content-Type: application/json

{
  "name": "Weight Loss Program",
  "description": "Program details for weight loss."
}

### Delete a health program
DELETE http://localhost:4000/api/programs/303081f1-ad93-4ec9-8718-2969bd6cf993


